project:
  type: book
  output-dir: docs

book:
  title: "Text as data"
  author: "Liza Wood"
  date: "June 8, 2023"
  
  search: true
  repo-url: https://github.com/d-rug/text-as-data
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01_text-data.qmd
    - 02_working-with-text.qmd
  
  sidebar:
    logo: https://github.com/d-rug/d-rug.github.io/raw/main/DRUG_final_cobalt.png
  site-url: https://d-rug.github.io

format:
  html:
    theme: cosmo
    number-sections: false